export const ErrorCode = {
  AUTH_INVALID: "AUTH_INVALID",
  AUTH_LOCKED: "AUTH_LOCKED",
  AUTH_EMAIL_UNVERIFIED: "AUTH_EMAIL_UNVERIFIED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  TOKEN_REUSED: "TOKEN_REUSED",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
